// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for reading one connection-scoped asynchronous thread setup handle.
 */
export type ThreadSetupStatusReadParams = { clientThreadId: string, };
