// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Failure categories exposed by asynchronous thread setup.
 *
 * These values intentionally avoid carrying provider errors, paths, prompts,
 * tool data, or other setup details across the client boundary.
 */
export type ThreadSetupFailureCode = "setupFailed" | "cancelled" | "timedOut";
