// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSetupFailureCode } from "./ThreadSetupFailureCode";

/**
 * A sanitized asynchronous thread setup status.
 */
export type ThreadSetupStatus = { "status": "pending" } | { "status": "ready", threadId: string, hostId: string, } | { "status": "failed", code: ThreadSetupFailureCode, };
